version: '3.8'

services:
  auth-service:
    build:
      context: ./Authentication
    container_name: auth-service
    ports:
      - "5000:5000"
    volumes:
      - ./Authentication:/app
    networks:
      - backend

  catalog-service:
    build:
      context: ./Catalog
    container_name: catalog-service
    ports:
      - "5001:5000"
    volumes:
      - ./Catalog:/app
    networks:
      - backend

  transaction-service:
    build:
      context: ./Transactions
    container_name: transaction-service
    ports:
      - "5002:5000"
    volumes:
      - ./Transactions:/app
    networks:
      - backend

networks:
  backend:
