version: '3.8'

services:
  catalog-service:
    build:
      context: ./
    container_name: catalog-service
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    networks:
      - backend


networks:
  backend:
