version: '3.8'

services:
  auth-service:
    build:
      context: ./
    container_name: auth-service
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    networks:
      - backend

networks:
  backend:
